### ISSUE TITLE
Unit Tests Failing

### ISSUE THREAD

**Issue by whammond4** [OpenTravel/otm-dex#1]
There are a few unit tests executed through `mvn test` which are failing, either due to invalid assertions or an unhandled exception being thrown. For reference, these errors occurred while using JDK 1.8.0u231 and running off the pom file in the root project directory. The test cases failing due to an invalid assertion are:

```
testInheritance(OTM_FX.FxBrowser.model.TestEnumerations)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError

testNotInitialized(OTM_FX.FxBrowser.TestImageManager)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<javafx.scene.image.Image@323e8306>

testStatic(OTM_FX.FxBrowser.TestImageManager)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<javafx.scene.image.Image@323e8306>

testNotInitialized(OTM_FX.FxBrowser.TestImageManager)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<javafx.scene.image.Image@323e8306>
```

The unit tests which are failing due to an unhandled exception are below, along with their respective stack traces:
```
basicTest(OTM_FX.FxBrowser.TestFxBaseUnmanaged)  Time elapsed: 2.047 sec  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.opentravel.application.common.AbstractOTMApplication.getController()Lorg/opentravel/application/common/AbstractMainWindowController;
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:302)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:245)
	at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:153)
	at org.opentravel.utilities.testutil.OtmFxRobot$1.evaluate(OtmFxRobot.java:291)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.opentravel.application.common.AbstractOTMApplication.getController()Lorg/opentravel/application/common/AbstractMainWindowController;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.get(WaitForAsyncUtils.java:697)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupApplication$6(ToolkitServiceImpl.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.opentravel.application.common.AbstractOTMApplication.getController()Lorg/opentravel/application/common/AbstractMainWindowController;
	at org.opentravel.utilities.testutil.AbstractFxTest.lambda$new$0(AbstractFxTest.java:65)
	at org.opentravel.utilities.testutil.OtmFxRobot.start(OtmFxRobot.java:270)
	at org.testfx.framework.junit.ApplicationAdapter.start(ApplicationAdapter.java:41)
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$0(ApplicationServiceImpl.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
	... 1 more

OTM_FX.FxBrowser.TestFxBrowserUnmanaged  Time elapsed: 0.001 sec  <<< ERROR!
java.io.IOException: Source file not found: C:\Users\WillHammond\workspace\otm\otm-dex\FxBrowser\src\test\resources\test-data.
	at org.opentravel.schemacompiler.repository.testutil.RepositoryTestUtils.copyContents(RepositoryTestUtils.java:99)
	at org.opentravel.schemacompiler.repository.testutil.AbstractRepositoryTest.setupWorkInProcessArea(AbstractRepositoryTest.java:85)
	at org.opentravel.schemacompiler.repository.testutil.AbstractRepositoryTest.setupWorkInProcessArea(AbstractRepositoryTest.java:65)
	at OTM_FX.FxBrowser.TestFxBrowserUnmanaged.setupTests(TestFxBrowserUnmanaged.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by xmldave** [comment]
This is the wrong project. Try:  https://github.com/OpenTravel/OTM-DE-Utilities/tree/master/otm-dex
